NHibernate C#/LojaWeb/LojaWeb/LojaWeb/Controllers/HerancaController.cs
using LojaWeb.DAO;
using LojaWeb.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class HerancaController : Controller
    {
        //private UsuariosDAO usuariosDAO;

        //public HerancaController(UsuariosDAO usuariosDAO)
        //{
        //    this.usuariosDAO = usuariosDAO;
        //}
        //public ActionResult FormPessoaFisica()
        //{
        //    return View();
        //}
        //public ActionResult AdicionaPessoaFisica(PessoaFisica pessoaFisica)
        //{
        //    usuariosDAO.Adiciona(pessoaFisica);
        //    return RedirectToAction("Index", "Usuarios");
        //}
        //public ActionResult FormPessoaJuridica()
        //{
        //    return View();
        //}
        //public ActionResult AdicionaPessoaJuridica(PessoaJuridica pessoaJuridica)
        //{
        //    usuariosDAO.Adiciona(pessoaJuridica);
        //    return RedirectToAction("Index", "Usuarios");
        //}
    }
}

NHibernate C#/LojaWeb/LojaWeb/LojaWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

NHibernate C#/LojaWeb/LojaWeb/LojaWeb/Controllers/ProdutosController.cs
using log4net;
using LojaWeb.Entidades;
using LojaWeb.Infra;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class ProdutosController : Controller
    {
        //
        // GET: /Produtos/

        public ActionResult Index()
        {

            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(Produto produto)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Visualiza(int id)
        {
            Produto p = new Produto();
            return View(p);
        }

        public ActionResult Atualiza(Produto produto)
        {
            return RedirectToAction("Index");
        }

        public ActionResult ProdutosComPrecoMinimo(double? preco)
        {
            ViewBag.Preco = preco;
            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }

        public ActionResult ProdutosDaCategoria(string nomeCategoria)
        {
            ViewBag.NomeCategoria = nomeCategoria;
            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }

        public ActionResult ProdutosDaCategoriaComPrecoMinimo(double? preco, string nomeCategoria)
        {
            ViewBag.Preco = preco;
            ViewBag.NomeCategoria = nomeCategoria;
            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }

        public ActionResult BuscaDinamica(double? preco, string nome, string nomeCategoria)
        {
            ViewBag.Preco = preco;
            ViewBag.Nome = nome;
            ViewBag.NomeCategoria = nomeCategoria;

            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }
        public ActionResult ListaPaginada(int? pagina)
        {
            int paginaAtual = pagina.GetValueOrDefault(1);
            ViewBag.Pagina = paginaAtual;
            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }
    }
}

NHibernate C#/LojaWeb/LojaWeb/LojaWeb/Controllers/UsuariosController.cs
using LojaWeb.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class UsuariosController : Controller
    {
        //
        // GET: /Usuarios/

        public ActionResult Index()
        {
            IList<Usuario> usuarios = new List<Usuario>();
            return View(usuarios);
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(Usuario usuario)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Visualiza(int id)
        {
            Usuario usuario = new Usuario();
            return View(usuario);
        }

        public ActionResult Atualiza(Usuario usuario)
        {
            return RedirectToAction("Index");
        }

    }
}

NHibernate C#/LojaWeb/LojaWeb/LojaWeb/Controllers/VendasController.cs
using LojaWeb.DAO;
using LojaWeb.Entidades;
using LojaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class VendasController : Controller
    {
        public ActionResult Index()
        {
            IList<Venda> vendas = new List<Venda>();
            return View(vendas);
        }
        public ActionResult ListaProdutos()
        {
            IList<Produto> produtos = new List<Produto>();
            ViewBag.ProdutosNoCarrinho = this.Carrinho.Produtos.Count;
            return View(produtos);
        }
        public ActionResult AdicionaProduto(int produtoId)
        {
            Produto produto = new Produto();
            this.Carrinho.Adiciona(produto);
            return RedirectToAction("ListaProdutos");
        }
        public ActionResult FechaPedido()
        {
            IList<Produto> produtos = this.Carrinho.Produtos;
            IList<Usuario> usuarios = new List<Usuario>();
            ViewBag.Usuarios = usuarios;
            return View(produtos);
        }
        public ActionResult CompletaPedido(int usuarioId)
        {
            Usuario usuario = new Usuario();
            Venda venda = this.Carrinho.CriaVenda(usuario);
            // grava venda
            this.Carrinho = new Carrinho();
            return RedirectToAction("Index");
        }
        public ActionResult LimpaCarrinho()
        {
            this.Carrinho = new Carrinho();
            return RedirectToAction("ListaProdutos");
        }

        // O Valor da propriedade Carrinho é armazenado na sessão
        private Carrinho Carrinho
        {
            get
            {
                Carrinho atual = Session["Carrinho"] as Carrinho;
                if (atual == null)
                {
                    atual = new Carrinho();
                    Session["Carrinho"] = atual;
                }
                return atual;
            }
            set
            {
                Session["Carrinho"] = value;
            }
        }
    }
}

NHibernate C#/LojaWeb/LojaWeb/LojaWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Caelum Online - NHibernate";
}

<h3>Produtos:</h3>
<ul>
    <li>@Html.ActionLink("Cadastro De Produtos", "Form", "Produtos")</li>
    <li>@Html.ActionLink("Lista De Produtos", "Index", "Produtos")</li>
    <li>@Html.ActionLink("Busca de Produtos por Preço", "ProdutosComPrecoMinimo", "Produtos")</li>
    <li>@Html.ActionLink("Busca de Produtos por Nome de Categoria", "ProdutosDaCategoria", "Produtos")</li>
    <li>@Html.ActionLink("Busca de Produtos por Nome de Categoria e Preço", "ProdutosDaCategoriaComPrecoMinimo", "Produtos")</li>
    <li>@Html.ActionLink("Busca Dinâmica de Produtos", "BuscaDinamica", "Produtos")</li>
    <li>@Html.ActionLink("Lista de Produtos Paginada", "ListaPaginada", "Produtos")</li>
</ul>

<h3>Categorias</h3>
<ul>
    <li>@Html.ActionLink("Cadastro de Categorias", "Form", "Categorias")</li>
    <li>@Html.ActionLink("Lista De Categorias", "Index", "Categorias")</li>
    <li>@Html.ActionLink("Busca De Categorias Por Nome", "BuscaPorNome", "Categorias")</li>
    <li>@Html.ActionLink("Quantidade de Produtos por Categoria", "NumeroDeProdutosPorCategoria", "Categorias")</li>
    <li>@Html.ActionLink("Lista de Categorias E Produtos", "CategoriasEProdutos", "Categorias")</li>
</ul>

<h3>Usuários</h3>
<ul>
    <li>@Html.ActionLink("Cadastro de Usuários", "Form", "Usuarios")</li>
    <li>@Html.ActionLink("Lista de Usuários", "Index", "Usuarios")</li>
    <li>@Html.ActionLink("Nova Pessoa Física", "FormPessoaFisica", "Heranca")</li>
    <li>@Html.ActionLink("Nova Pessoa Jurídica", "FormPessoaJuridica", "Heranca")</li>
</ul>

<h3>Vendas</h3>
<ul>
    <li>@Html.ActionLink("Lista de Vendas", "Index", "Vendas")</li>
    <li>@Html.ActionLink("Comprar", "ListaProdutos", "Vendas")</li>
</ul>