NHibernate C#/LojaWeb-FInal/LojaWeb/Controllers/CategoriasController.cs
using LojaWeb.DAO;
using LojaWeb.Entidades;
using LojaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class CategoriasController : Controller
    {
        private CategoriasDAO dao;
        //
        // GET: /Categorias/

        public ActionResult Index()
        {
            IList<Categoria> categorias = new List<Categoria>();
            return View(categorias);
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(Categoria categoria)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
     
            return RedirectToAction("Index");
        }

        public ActionResult Visualiza(int id)
        {
            Categoria categoria = new Categoria();
            return View(categoria);
        }

        public ActionResult Atualiza(Categoria categoria)
        {
            return RedirectToAction("Index");
        }

        public ActionResult CategoriasEProdutos()
        {
            IList<Categoria> categorias = new List<Categoria>();
            return View(categorias);
        }

        public ActionResult BuscaPorNome(string nome)
        {
            IList<Categoria> categorias = dao.BuscaPorNome(nome);
            return View(categorias);
        }

        public ActionResult NumeroDeProdutosPorCategoria()
        {
            IList<ProdutosPorCategoria> lista = dao.ListaNumeroDeProdutosPorCategoria();

            return View(lista);
        }
    }
}

NHibernate C#/LojaWeb-FInal/LojaWeb/Views/Categorias/BuscaPorNome.cshtml
@model System.Collections.Generic.IEnumerable<LojaWeb.Entidades.Categoria>
@{
    ViewBag.Title = "BuscaPorNome";
}

<h2>Busca Por Nome</h2>

<form action="@Url.Action("BuscaPorNome", "Categorias")" method="get">
    <label>
        Nome:
        <input name="nome" type="text" value="@ViewBag.Nome"/>
    </label>
    <input type="submit" value="Buscar"/>
</form>

@Html.Partial("_ListaCategorias", @Model)

NHibernate C#/LojaWeb-FInal/LojaWeb/Views/Categorias/CategoriasEProdutos.cshtml
@{
    ViewBag.Title = "CategoriasEProdutos";
}

<h2>CategoriasEProdutos</h2>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Produtos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var categoria in @Model)
        {
            <tr>
                <td>@categoria.Id</td>
                <td>@categoria.Nome</td>
                <td>
                    @foreach (var produto in @categoria.Produtos)
                    {
                        @(produto.Nome + " | ")
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

NHibernate C#/LojaWeb-FInal/LojaWeb/Views/Categorias/Form.cshtml
@{
    ViewBag.Title = "Form";
}

<h2>Nova Categoria</h2>

<form action="@Url.Action("Adiciona", "Categorias")" method="post">
    <label>
        Nome:
        <input type="text" name="categoria.Nome" />
    </label>
    <input type="submit" value="Adicionar"/>
</form>

NHibernate C#/LojaWeb-FInal/LojaWeb/Views/Categorias/Index.cshtml
@model System.Collections.Generic.IEnumerable<LojaWeb.Entidades.Categoria>
@{
    ViewBag.Title = "Index";
}

<h2>Lista de Categorias</h2>

@Html.Partial("_ListaCategorias", @Model)

NHibernate C#/LojaWeb-FInal/LojaWeb/Views/Categorias/NumeroDeProdutosPorCategoria.cshtml
@{
    ViewBag.Title = "ProdutosPorCategoria";
}

<h2>ProdutosPorCategoria</h2>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome Categoria</th>
            <th>Número De Produtos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produtosPorCategoria in @Model)
        {
            <tr>
                <td>@produtosPorCategoria.Categoria.Id</td>
                <td>@produtosPorCategoria.Categoria.Nome</td>
                <td>@produtosPorCategoria.NumeroDeProdutos</td>
            </tr>
        }
    </tbody>
</table>

NHibernate C#/LojaWeb-FInal/LojaWeb/Views/Categorias/Visualiza.cshtml
@{
    ViewBag.Title = "Visualiza";
}

<h2>Categoria - @Model.Nome</h2>

<form action="@Url.Action("Atualiza", "Categorias")" method="post">
    <input type="hidden" name="categoria.Id" value="@Model.Id" />
    <label>
        Nome:
        <input type="text" name="categoria.Nome" value="@Model.Nome" />
    </label>
    <input type="submit" value="Alterar" />
</form>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome Produto</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in @Model.Produtos)
        {
            <tr>
                <td>@produto.Id</td>
                <td>@produto.Nome</td>
                <td>@produto.Preco</td>
            </tr>
        }
    </tbody>
</table>